### ISSUE TITLE
[错误报告]：Chrome切换到设定页报错

### ISSUE THREAD

**Issue by liheji** [jxxghp/MoviePilot-Frontend#133]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot-Frontend/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot-Frontend/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.2-1

### 问题描述

在 zerotier 网络下，使用 chrome 打开 MOVIEPILOT ，切换到 http://my-pc-host:3000/#/setting 标签时报错如下

```js
TypeError: Cannot create property 'u' on number '1'
    at V5 (index.js:987:20788)
    at index.js:987:20973
    at setting.js:20:4339
```

点开代码后，发现错误在以下代码，Firefox 访问并没有出现同样的错误

```js
function V5(e, t, l=ze, a=!1) {
    if (l) {
        const n = l[e] || (l[e] = [])
          , i = t.__weh || (t.__weh = (...s)=>{
            if (l.isUnmounted)
                return;
            zl();
            const p = il(l)
              , h = ut(t, l, e, s);
            return p(),
            Ml(),
            h
        }
        );
        return a ? n.unshift(i) : n.push(i),
        i
    }
}
```

Firefox版本：126.0.1 (64 位)
Chrome版本：版本 125.0.6422.113（正式版本） （64 位）

### 发生问题时系统日志和配置文件

```bash
仅前端出现问题，暂无日志
```

**Comment by jxxghp** [comment]
清浏览器缓存
