### ISSUE TITLE
[错误报告]：PC上浏览器无法打开文件管理

### ISSUE THREAD

**Issue by yonly1314** [jxxghp/MoviePilot-Frontend#156]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot-Frontend/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot-Frontend/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.4-1

### 问题描述

PC上 edge，chrome，搜狗浏览器都无法访问 文件管理，打开是空白页面。尝试过清理所有的浏览器缓存，都没效果
IOS上，chrome可以正常访问文件管理
![image](https://github.com/jxxghp/MoviePilot-Frontend/assets/83340866/2e4d7c1b-bbd5-481b-993c-4980794a3ca9)

### 发生问题时系统日志和配置文件

```bash
:3000/#/filemanager:1  The resource http://10.118.8.70:3000/index.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

**Comment by jxxghp** [comment]
最新版本已修复
