### ISSUE TITLE
[Feature Request]: 前端 JS 可以考虑加哈希或者时间戳

### ISSUE THREAD

**Issue by loongcheung** [jxxghp/MoviePilot-Frontend#161]
### 当前程序版本

1.9.6

### 功能改进

现在前端 JS 只有文件名，由于浏览器静态文件缓存导致必须清缓存，而手机端不好清除干净。可以考虑给 JS 文件名后面加哈希或者时间戳，这样升级后就是新的版本 JS

**Comment by jxxghp** [comment]
@loongcheung 最早就是这样的，升级后开始界面会无限转圈。不过最新的镜像已经默认不缓存JS文件了，亲测手机端只要杀掉后台重新开就行了
