### ISSUE TITLE
[RFC]将现有`手动整理`中的`目的路径`输入方式

### ISSUE THREAD

**Issue by wikrin** [jxxghp/MoviePilot-Frontend#247]
### 背景 or 问题

01f63a4 的方式仅需`两次`点击即可键入`目的路径`
c956e27 改为了一级一级选择, 步骤繁多, 并且展开子文件夹也需一次点击
这个提交是为了解决用户输入了一个`媒体库目录`的子目录,导致未按预期进行整理,而是整理到了设定的`媒体库目录`并创建了`分类`
这个错误原因在于后端`DirectoryHelper.get_dir()`使用了`dest_path.is_relative_to()`导致用户输入的`目的目录`匹配了设定的`目录配置`

### 目标 & 方案简述

目前已实现根据开关进行分类
在输入方式为下拉时:
- 大多数情况下, 整理的目标路径是固定的, 在`存储 & 目录` 中配置
- 直接使用下拉中的`预选项` 将 `目的存储 & 整理方式 & 刮削元数据 & 分类策略` 的选项调整为目录的`配置`, 当然也可以手动修改
- `极少数`整理到`其他目录`的情况也可以`直接编辑`
方案:
- revert c956e27 为 01f63a4
- 将后端`DirectoryHelper.get_dir()`中的`if dest_path and not dest_path.is_relative_to(d.library_path)`判断改为`if dest_path and dest_path != Path(d.library_path)`
-- 修改原因为`dest_path`仅在手动整理有入参, 进行处理会造成混乱, 所以在其他`自动整理`逻辑中尽量`不要传入此参数`

**Comment by jxxghp** [comment]
@wikrin 我想想，还没空看
