### ISSUE TITLE
[错误报告]：搜索结果的筛选出现问题。

### ISSUE THREAD

**Issue by BenZinaDaze** [jxxghp/MoviePilot-Frontend#28]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot-Frontend/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot-Frontend/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.8

### 问题描述

1. 站点筛选，切换站点筛选后，之前某次筛选的结果还会继续出现。如图，憨憨的结果会继续出现在之后的站点筛选结果中。
 ![1693281340736.png](https://img1.nmd.im/2023/08/29/64ed6c4175cb9.png)
2. 集数筛选会包含其他集数，不是打包合集的原因。
 ![1693281228651.png](https://img1.nmd.im/2023/08/29/64ed6bd06f4fb.png)
3. 筛选多了  种子重复显示了多次
 ![1693281291103.png](https://img1.nmd.im/2023/08/29/64ed6c0dd4187.png)

**Comment by jxxghp** [comment]
@thofx 大佬看看
