### ISSUE TITLE
[错误报告]：webui进程频繁死机，无法访问

### ISSUE THREAD

**Issue by lijl9696** [jxxghp/MoviePilot-Frontend#49]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot-Frontend/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot-Frontend/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.2.9

### 问题描述

宿主机是unraid，MP运行一段时间后，后台服务正常运行，订阅、同步之类正常，TG机器人也能正常用，但是前端UI进不去了，怀疑是webui的进程死了。
在TG群里有多位朋友遇到共同问题，确定不是个人配置问题。

**Comment by jxxghp** [comment]
是docker运行吗？

**Comment by lijl9696** [comment]
是的，unraid下自带的docker管理运行的，tg群里几个遇到同样问题的与我情况一致。我准备尝试用docker
compose安装管理试试，跑两天看看会不会有类似情况。

在 2023年10月8日星期日，jxxghp ***@***.***> 写道：

**Comment by DDSDerek** [comment]
> 是docker运行吗？

我怀疑是nginx进程被杀死了或者崩溃了，因为没有底层的进程管理器，所以不会重新启动nginx
