### ISSUE TITLE
[错误报告]：日志显示不全

### ISSUE THREAD

**Issue by xiaobaiwaf** [jxxghp/MoviePilot-Frontend#67]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot-Frontend/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot-Frontend/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.5.7-2

### 问题描述

日志碰到较长条目时显示不全，希望可以换行显示
![image](https://github.com/jxxghp/MoviePilot-Frontend/assets/97422881/60c936e4-6c65-475d-addb-e60af3708027)

**Comment by jxxghp** [comment]
下面有滚动条吧
