### ISSUE TITLE
[Feature Request]: 已安装插件也显示安装次数

### ISSUE THREAD

**Issue by DzAvril** [jxxghp/MoviePilot-Frontend#89]
### 当前程序版本

v1.7.6-1

### 功能改进

新功能在插件市场上可以看到已经下载次数，但是插件安装后就看不到了。
希望可以增加功能，在安装后仍然可以看到下载次数。作为开发者可以实时看到自己插件的下载次数还是很有成就感的。

**Comment by jxxghp** [comment]
@DzAvril 这个可以有

**Comment by jxxghp** [comment]
@DzAvril 大佬tg联系下我，拉你进群
